version: '3.8'

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb_dev
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: mydb
      MARIADB_USER: myuser
      MARIADB_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: springboot-app
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/mydb
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: secret
    networks:
      - backend

  frontend:
    build:
      context: ./Zapp_Project
      dockerfile: Dockerfile
    container_name: vue-frontend
    #ports:
      #- "80"
    networks:
      - backend
    depends_on:
      - app

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  db_data:

