# Use root/root as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: berufdb
      MYSQL_USER: berufuser
      MYSQL_PASSWORD: berufpass

    # (this is just an example, not intended to be a production configuration)
    ports:
      - 3306:3306
