version: '3.8'

services:
  mariadb:
    image: mariadb:11.3
    container_name: mariadb_dev
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: mydb
      MARIADB_USER: appuser
      MARIADB_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - backend

  app:
    build: .
    container_name: springboot-app
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/mydb
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: secret
    networks:
      - backend

  frontend:
    build:
      context: ../ZAPP_Project
      dockerfile: Dockerfile
    container_name: vue-frontend
    ports:
      - "5173:80"
    networks:
      - backend
    depends_on:
      - app

networks:
  backend:
    driver: bridge
