version: '3.8'

services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    networks:
      - backend

  frontend:
    build:
      context: ../ZAPP_Project
      dockerfile: Dockerfile
    container_name: vue-frontend
    networks:
      - backend
    depends_on:
      - app

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - backend

networks:
  backend:
    driver: bridge
